dataset:
  params:
    allowed:
      colors:
      - red
      - green
      - blue
      shapes:
      - square
      - circle
      - triangle
      - plus
      textures:
      - solid
      - spots_polka
      - stripes_diagonal
    allowed_combinations:
    - - square
      - green
      - solid
    - - square
      - green
      - spots_polka
    - - square
      - green
      - stripes_diagonal
    - - square
      - blue
      - solid
    - - square
      - blue
      - spots_polka
    - - square
      - blue
      - stripes_diagonal
    - - circle
      - green
      - solid
    - - circle
      - green
      - spots_polka
    - - circle
      - green
      - stripes_diagonal
    - - circle
      - blue
      - solid
    - - circle
      - blue
      - spots_polka
    - - circle
      - blue
      - stripes_diagonal
    - - triangle
      - red
      - solid
    - - triangle
      - red
      - spots_polka
    - - triangle
      - red
      - stripes_diagonal
    - - triangle
      - green
      - solid
    - - triangle
      - green
      - spots_polka
    - - triangle
      - green
      - stripes_diagonal
    - - triangle
      - blue
      - solid
    - - triangle
      - blue
      - spots_polka
    - - triangle
      - blue
      - stripes_diagonal
    - - plus
      - green
      - solid
    - - plus
      - green
      - spots_polka
    - - plus
      - green
      - stripes_diagonal
    - - plus
      - blue
      - solid
    - - plus
      - blue
      - spots_polka
    - - plus
      - blue
      - stripes_diagonal
    class_configs:
    - color: green
      shape: square
      texture: solid
    - color: green
      shape: square
      texture: spots_polka
    - color: green
      shape: square
      texture: stripes_diagonal
    - color: green
      shape: square
      texture: null
    - color: blue
      shape: square
      texture: solid
    - color: blue
      shape: square
      texture: spots_polka
    - color: blue
      shape: square
      texture: stripes_diagonal
    - color: blue
      shape: square
      texture: null
    - color: null
      shape: square
      texture: solid
    - color: null
      shape: square
      texture: spots_polka
    - color: null
      shape: square
      texture: stripes_diagonal
    - color: green
      shape: circle
      texture: solid
    - color: green
      shape: circle
      texture: spots_polka
    - color: green
      shape: circle
      texture: stripes_diagonal
    - color: green
      shape: circle
      texture: null
    - color: blue
      shape: circle
      texture: solid
    - color: blue
      shape: circle
      texture: spots_polka
    - color: blue
      shape: circle
      texture: stripes_diagonal
    - color: blue
      shape: circle
      texture: null
    - color: null
      shape: circle
      texture: solid
    - color: null
      shape: circle
      texture: spots_polka
    - color: null
      shape: circle
      texture: stripes_diagonal
    - color: red
      shape: triangle
      texture: solid
    - color: red
      shape: triangle
      texture: spots_polka
    - color: red
      shape: triangle
      texture: stripes_diagonal
    - color: red
      shape: triangle
      texture: null
    - color: green
      shape: triangle
      texture: solid
    - color: green
      shape: triangle
      texture: spots_polka
    - color: green
      shape: triangle
      texture: stripes_diagonal
    - color: green
      shape: triangle
      texture: null
    - color: blue
      shape: triangle
      texture: solid
    - color: blue
      shape: triangle
      texture: spots_polka
    - color: blue
      shape: triangle
      texture: stripes_diagonal
    - color: blue
      shape: triangle
      texture: null
    - color: null
      shape: triangle
      texture: solid
    - color: null
      shape: triangle
      texture: spots_polka
    - color: null
      shape: triangle
      texture: stripes_diagonal
    - color: green
      shape: plus
      texture: solid
    - color: green
      shape: plus
      texture: spots_polka
    - color: green
      shape: plus
      texture: stripes_diagonal
    - color: green
      shape: plus
      texture: null
    - color: blue
      shape: plus
      texture: solid
    - color: blue
      shape: plus
      texture: spots_polka
    - color: blue
      shape: plus
      texture: stripes_diagonal
    - color: blue
      shape: plus
      texture: null
    - color: null
      shape: plus
      texture: solid
    - color: null
      shape: plus
      texture: spots_polka
    - color: null
      shape: plus
      texture: stripes_diagonal
    - color: red
      shape: null
      texture: solid
    - color: red
      shape: null
      texture: spots_polka
    - color: red
      shape: null
      texture: stripes_diagonal
    - color: green
      shape: null
      texture: solid
    - color: green
      shape: null
      texture: spots_polka
    - color: green
      shape: null
      texture: stripes_diagonal
    - color: blue
      shape: null
      texture: solid
    - color: blue
      shape: null
      texture: spots_polka
    - color: blue
      shape: null
      texture: stripes_diagonal
    dataset_kwargs:
      element_n: 4
      element_seed: 456
      element_size: 64
      element_size_delta: 16
      img_size: 256
      loc_seed: 789
      n: 5000
  target: elements.classes.ConceptElementDatasetCreator
